name: buf-pull-request
on: 
    push:
    pull_request:
        branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      # Install `protoc` - needed to generate code
      - uses: arduino/setup-protoc@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
            input: "proto"
      - uses: bufbuild/buf-breaking-action@v1
        with:
            input: "proto"
            # The 'main' branch of the GitHub repository that defines the module.
            # Note we specify the subdir to compare against.
            against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=proto"
      - name: Installing protoc-gen-go
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Build
        run: |
          buf mod update
          buf generate proto
